---
title: "Covid LA Cities"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Libraries, include = FALSE}
library(forecast)
library(ggplot2)
```


```{r Data, echo=FALSE}
#reading in data into useable dataframe
df = read.csv(file = "LA_cities_cases.csv", header = FALSE)
df[1,1] = "Date"
df = t(df)
colnames(df) <- as.character(unlist(df[1,])) #sets cities as column names
df = df[-1, ] #removes first row entries which contained column names
df = as.data.frame(df)
Date = as.Date(df$Date, format = "%d-%m")


#severity data
severity_df = read.csv(file = "LA_cities_severity.csv", header = FALSE)
severity_df = t(severity_df)
colnames(severity_df) <- as.character(unlist(severity_df[1,]))
severity_df = severity_df[-1, ]
severity_df = as.data.frame(severity_df)
```



```{r Hollywood Hills}
#Save rates as a timeseries
Hollywood_timeseries = as.numeric(ts(df$`Los Angeles - Hollywood Hills`))

#Fit to arima
Hollywood_Severity = as.numeric(ts(severity_df$`Los Angeles - Hollywood Hills`))
Hollywood_fit = auto.arima(Hollywood_timeseries, xreg = Hollywood_Severity)
print(Hollywood_fit)

#forecast with regressors
Hollywood_Severity = as.numeric(ts(severity_df$`Los Angeles - Hollywood Hills`))
Hollywood_Sev_Pred = as.numeric(forecast(Hollywood_Severity)$mean) #prediction for future Hollywood_Severity values

autoplot(forecast(Hollywood_fit, xreg = Hollywood_Sev_Pred)) +
  xlab("Days Since Jan 21st") +
  ylab("Covid Cases")
```



```{r Hollywood Error Test}
#taking first few data points and using it to train model
first_95 = head(df$`Los Angeles - Hollywood Hills`, length(df$`Los Angeles - Hollywood Hills`) - 10)
first_95ts = ts(as.numeric(first_95))


sev_first_95 = head(severity_df$`Los Angeles - Hollywood Hills`, length(severity_df$`Los Angeles - Hollywood Hills`) - 10)

sev_first_95ts = ts(as.numeric(sev_first_95))

#Model trained on first days
fit95 = auto.arima(first_95ts, xreg = sev_first_95ts)
sev_95pred = as.numeric(forecast(sev_first_95ts)$mean)

#predictions
pred10 = as.data.frame(as.numeric(forecast(fit95, xreg = sev_95pred)$mean)) #predict last 10 days of dataset
print(pred10)

#actual values for last 10 days
last_10_Hollywood = as.data.frame(as.numeric(tail(df$`Los Angeles - Hollywood Hills`, 10)))

#error
(pred10 - last_10_Hollywood)/last_10_Hollywood
```



```{r City Prediction Function, include = FALSE}
city_prediction_reg = function(city) {
  #Prediction with severity values as regressors
  city_timeseries = as.numeric(ts(df[,city]))
  
  #Fit to arima
  city_Severity = as.numeric(ts(severity_df[,city]))
  city_fit = auto.arima(city_timeseries, xreg = city_Severity)
  
  #forecast with regressors
  city_Sev_Pred = as.numeric(forecast(city_Severity)$mean) #prediction for future city_Severity values
  
  autoplot(forecast(city_fit, xreg = city_Sev_Pred)) +
    xlab("Days Since Jan 21st") +
    ylab("Covid Cases")
}

city_prediction_nreg = function(city) {
  #Prediction without severity values as regressors
  city_timeseries = as.numeric(ts(df[,city]))
  city_fit = auto.arima(city_timeseries)

  #forecast no regressors  
  autoplot(forecast(city_fit)) +
    xlab("Days Since Jan 21st") +
    ylab("Covid Cases")
}

city_prediction = function(city) {
  #complete city prediction function
  
  tryCatch(city_prediction_reg(city),
    error = function(c) {
      #Sometimes an arima model can't be found with the severity values, so an arima model w/o severity regressors is used instead
      city_prediction_nreg(city)
      }
    
    )
  
}

print(colnames(df)) #all possible city input values
```


```{r Rancho Dominguez}
city_prediction("Rancho Dominguez")
```


```{r Errors, include = FALSE}
city_pred_reg_error = function(city) {
  #prediction and error checking using severity values
  #taking first few data points and using it to train model
  first_95 = head(df[,city], length(df[,city]) - 10)
  first_95ts = ts(as.numeric(first_95))
  sev_first_95 = head(severity_df[,city], length(severity_df[,city]) - 10)
  sev_first_95ts = ts(as.numeric(sev_first_95))

  #Model trained on first days
  fit95 = auto.arima(first_95ts, xreg = sev_first_95ts)
  sev_95pred = as.numeric(forecast(sev_first_95ts)$mean)

  #predict last 10 days of dataset
  pred10 = as.data.frame(as.numeric(forecast(fit95, xreg = sev_95pred)$mean))   
  #actual values for last 10 days
  last_10_city = as.data.frame(as.numeric(tail(df[,city], 10)))

  #error
  return((pred10 - last_10_city)/last_10_city)
}

city_pred_nreg_error = function(city) {
  #prediction and error checking without severity values
  #taking first few data points and using it to train model
  first_95 = head(df[,city], length(df[,city]) - 10)
  first_95ts = ts(as.numeric(first_95))
  
  #Model trained on first days
  fit95 = auto.arima(first_95ts)

  #predict last 10 days of dataset
  pred10 = as.data.frame(as.numeric(forecast(fit95)$mean))

  #actual values for last 10 days
  last_10_city = as.data.frame(as.numeric(tail(df[,city], 10)))

  #error
  return((pred10 - last_10_city)/last_10_city)
}

```

```{r Model Comparisons}
#compare model errors with and without severity scores
#some cities don't work with the severity values because an arima model can't be fit
reg = city_pred_reg_error("Los Angeles - Century City")
nreg = city_pred_nreg_error("Los Angeles - Century City")

print(reg) #error with severity values as regression variables
print(nreg) #error w/o severity values
```


