---
title: "Forecast of COVID-19 Cases in LA Cities"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Libraries, include = FALSE}
library(forecast)
library(ggplot2)
```

```{r Data, echo=FALSE}
#reading in data into useable dataframe
df = read.csv(file = "LA_cities_cases.csv", header = FALSE)
df[1,1] = "Date"
df = t(df)
colnames(df) <- as.character(unlist(df[1,])) #sets cities as column names
df = df[-1, ] #removes first row entries which contained column names
df = as.data.frame(df)
Date = as.Date(df$Date, format = "%d-%mon")
df$Date = NULL #remove "Date" column

#severity data
severity_df = read.csv(file = "LA_cities_severity.csv", header = FALSE)
severity_df = t(severity_df)
colnames(severity_df) <- as.character(unlist(severity_df[1,]))
severity_df = severity_df[-1, ]
severity_df = as.data.frame(severity_df)
```

```{r City Prediction Function, include = FALSE}
city_prediction_reg = function(city) {
  #Prediction with severity values as regressors
  city_timeseries = as.numeric(ts(df[,city]))
  
  #Fit to arima
  city_Severity = as.numeric(ts(severity_df[,city]))
  city_fit = auto.arima(city_timeseries, xreg = city_Severity)
  
  #forecast with regressors
  city_Sev_Pred = as.numeric(forecast(city_Severity)$mean) #prediction for future city_Severity values
  
  autoplot(forecast(city_fit, xreg = city_Sev_Pred)) +
    xlab("Days Since Jan 21st") +
    ylab("Covid Cases")
}

city_prediction_nreg = function(city) {
  #Prediction without severity values as regressors
  city_timeseries = as.numeric(ts(df[,city]))
  city_fit = auto.arima(city_timeseries)

  #forecast no regressors  
  autoplot(forecast(city_fit)) +
    xlab("Days Since Jan 21st") +
    ylab("Covid Cases")
}

city_prediction = function(city) {
  #complete city prediction function
  
  tryCatch(city_prediction_reg(city),
    error = function(c) {
      #Sometimes an arima model can't be found with the severity values, so an arima model w/o severity regressors is used instead
      city_prediction_nreg(city)
      }
    
    )
  
}
```

```{r Errors, include = FALSE}
city_pred_reg_error = function(city) {
  #prediction and error checking using severity values
  #taking first few data points and using it to train model
  first_95 = head(df[,city], length(df[,city]) - 10)
  first_95ts = ts(as.numeric(first_95))
  sev_first_95 = head(severity_df[,city], length(severity_df[,city]) - 10)
  sev_first_95ts = ts(as.numeric(sev_first_95))

  #Model trained on first days
  fit95 = auto.arima(first_95ts, xreg = sev_first_95ts)
  sev_95pred = as.numeric(forecast(sev_first_95ts)$mean)

  #predict last 10 days of dataset
  pred10 = as.data.frame(as.numeric(forecast(fit95, xreg = sev_95pred)$mean))   
  #actual values for last 10 days
  last_10_city = as.data.frame(as.numeric(tail(df[,city], 10)))

  #error
  errors = (pred10 - last_10_city)/last_10_city
  colnames(errors) = "Errors w/ Severity Values"
  return(errors)
}

city_pred_nreg_error = function(city) {
  #prediction and error checking without severity values
  #taking first few data points and using it to train model
  first_95 = head(df[,city], length(df[,city]) - 10)
  first_95ts = ts(as.numeric(first_95))
  
  #Model trained on first days
  fit95 = auto.arima(first_95ts)

  #predict last 10 days of dataset
  pred10 = as.data.frame(as.numeric(forecast(fit95)$mean))

  #actual values for last 10 days
  last_10_city = as.data.frame(as.numeric(tail(df[,city], 10)))

  #error
  errors = (pred10 - last_10_city)/last_10_city
  colnames(errors) = "Errors w/o Severity Values"
  return(errors)
}

city_pred_error = function(city) {
  sev_reg = city_pred_reg_error(city)
  n_sev_reg = city_pred_nreg_error(city)
  return(cbind(sev_reg, n_sev_reg))
}
```

```{r Cumulative City Prediction Function, include = FALSE}
cum_city_prediction_reg = function(city) {
  #Prediction with severity values as regressors
  city_timeseries = as.numeric(ts(cumsum(df[,city])))
  
  #Fit to arima
  city_Severity = as.numeric(ts(severity_df[,city]))
  city_fit = auto.arima(city_timeseries, xreg = city_Severity)
  
  #forecast with regressors
  city_Sev_Pred = as.numeric(forecast(city_Severity)$mean) #prediction for future city_Severity values
  
  autoplot(forecast(city_fit, xreg = city_Sev_Pred)) +
    xlab("Days Since Jan 21st") +
    ylab("Covid Cases")
}

cum_city_prediction_nreg = function(city) {
  #Prediction without severity values as regressors
  city_timeseries = as.numeric(ts(cumsum(df[,city])))
  city_fit = auto.arima(city_timeseries)

  #forecast no regressors  
  autoplot(forecast(city_fit)) +
    xlab("Days Since Jan 21st") +
    ylab("Covid Cases")
}

city_prediction = function(city) {
  #complete city prediction function
  
  tryCatch(city_prediction_reg(city),
    error = function(c) {
      #Sometimes an arima model can't be found with the severity values, so an arima model w/o severity regressors is used instead
      city_prediction_nreg(city)
      }
    
    )
  
}
```

## Covid Forecasts by City

```{r Inputs, echo=FALSE}
inputPanel(
  selectInput(inputId = "city", 
                label = "City:",
                choices = colnames(df)
                )
  )
```

```{r Plot Forecasts, echo = FALSE}
renderPlot(city_prediction_reg(input$city))

renderPlot(city_prediction_nreg(input$city))
```


## Prediction Errors of Last 10 Days

```{r Errors Tables, echo = FALSE}
renderDataTable(city_pred_error(input$city))
```

